# -*- coding: utf-8 -*-
"""Random_Sample_Testing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14pOpwR2uuAsFvEzKWaSYO9hm5JL1WaUn
"""

import pandas as pd
import random

!pip install -U -q PyDrive
import os
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

local_download_path = os.path.expanduser('~/data')
try:
  os.makedirs(local_download_path)
except: pass

# 2. Auto-iterate using the query syntax
#    https://developers.google.com/drive/v2/web/search-parameters
file_list = drive.ListFile(
    {'q': "'1EDEvz9CFck1YTjQc5LqHzWkWL7PZgZ3R' in parents"}).GetList()

for f in file_list:
  # 3. Create & download by id.
  print('title: %s, id: %s' % (f['title'], f['id']))
  fname = os.path.join(local_download_path, f['title'])
  print('downloading to {}'.format(fname))
  f_ = drive.CreateFile({'id': f['id']})
  f_.GetContentFile(fname)

from google.colab import drive
drive.mount('/content/drive')

filename = "/content/drive/MyDrive/election2020tweetsConsolidated.csv"
n = sum(1 for line in open(filename)) - 1
s = 1000
skip = sorted(random.sample(range(1,n+1),n-s)) 
df = pd.read_csv(filename, skiprows=skip)
df.to_csv('random_sample_data.csv')